### ISSUE TITLE
leaderbord

### ISSUE THREAD

**Issue by facinetm14** [mochan42/ft_transcendence#62]
Display 5 - 10 top players, who won the most xp. Then the user could request them to be friend.  Otherwise how would you like to organize the friendship experience ?

Thanks.

**Comment by pmeising** [comment]
Sounds good! I'll implement that on the Home page I was thinking.

On the last commit where I introduced the Matchmaking screen for the Pong game PvP, I also wrote a little UserCard. That one I would like to reuse for the Homepage together with a Leaderboard and Chat window.

**Comment by pmeising** [comment]
Update Leaderboard:


![Image](https://github.com/mochan42/ft_transcendence/assets/96015618/36ae9776-2cd9-44ee-aecd-b3ea25d8f7d2)
